from os import getenv

from dotenv import load_dotenv

load_dotenv("config.env")

API_HASH = "33bf1d586e5fdfd9e66aaa52a576935a"
API_ID = 19685518
STRING_SESSION1 = getenv("STRING1", "")
STRING_SESSION2 = getenv("STRING2", "")
STRING_SESSION3 = getenv("STRING3", "")
STRING_SESSION4 = getenv("STRING4", "")
STRING_SESSION5 = getenv("STRING5", "")
STRING_SESSION6 = getenv("STRING6", "")
STRING_SESSION7 = getenv("STRING7", "")
STRING_SESSION8 = getenv("STRING8", "")
STRING_SESSION9 = getenv("STRING9", "")
STRING_SESSION10 = getenv("STRING10", "")

STRING_SESSION11 = getenv("STRING11", "")
STRING_SESSION12 = getenv("STRING12", "")
STRING_SESSION13 = getenv("STRING13", "")
STRING_SESSION14 = getenv("STRING14", "")
STRING_SESSION15 = getenv("STRING15", "")
STRING_SESSION16 = getenv("STRING16", "")
STRING_SESSION17 = getenv("STRING17", "")
STRING_SESSION18 = getenv("STRING18", "")
STRING_SESSION19 = getenv("STRING19", "")
STRING_SESSION20 = getenv("STRING20", "")

STRING_SESSION21 = getenv("STRING21", "")
STRING_SESSION22 = getenv("STRING22", "")
STRING_SESSION23 = getenv("STRING23", "")
STRING_SESSION24 = getenv("STRING24", "")
STRING_SESSION25 = getenv("STRING25", "")
STRING_SESSION26 = getenv("STRING26", "")
STRING_SESSION27 = getenv("STRING27", "")
STRING_SESSION28 = getenv("STRING28", "")
STRING_SESSION29 = getenv("STRING29", "")
STRING_SESSION30 = getenv("STRING30", "")
